### PR TITLE
fixed macct name generation for qcow2 in linbo_cmd

### PR DESCRIPTION
**Pull request by PLanB2008**
As mentioned in Issue #67

### CODE REVIEW

**Comment by HappyBasher** [comment]
Sorry, I don't understand that. macct files are always bundled with a certain image file, so the filename has to be always image.qcow2.macct.

**Comment by PLanB2008** [comment]
Then one should possibly rewrite the naming of the image files. When I look into an image folder I'm greeted with these files:

```
root@server:/srv/linbo/images# tree
.
├── demo_focal
│   ├── demo_focal.macct
│   ├── demo_focal.qcow2
│   ├── demo_focal.qcow2.desc
│   ├── demo_focal.qcow2.info
│   └── demo_focal.qcow2.torrent
└── demo_win10-21h1_generic
    ├── demo_win10-21h1_generic.macct
    ├── demo_win10-21h1_generic.prestart
    ├── demo_win10-21h1_generic.qcow2
    ├── demo_win10-21h1_generic.qcow2.desc
    ├── demo_win10-21h1_generic.qcow2.info
    ├── demo_win10-21h1_generic.qcow2.macct
    ├── demo_win10-21h1_generic.qcow2.torrent
    └── demo_win10-21h1_generic.reg

2 directories, 13 files
```

demo_win10-21h1_generic.qcow2.macct I created myself by copying the other file. I dont get why prestart and reg does not have the qcow2 extension but all the other files have. This is kind of random and should be the same for all files which is IMHO without the qcow2 part.

**Comment by HappyBasher** [comment]
The file demo_win10-21h1_generic.macct is obviously a remnant of an older linbo version. Current versions use the naming scheme mentioned above.

**Comment by HappyBasher** [comment]
Since 4.0.0-0beta6 the current naming scheme is used.

**Comment by PLanB2008** [comment]
So reg and prestart are correct without the qcow2 extension and all others have to keep them?
The file demo_win10-21h1_generic.macct got created during the conversion of the image from cloop to qcow2

**Comment by HappyBasher** [comment]
So `linbo-cloop2qcow2` has to be fixed.

**Pull request closed without merging**
